"""
EnemyFactory — dynamically generates enemy Characters scaled to player power.

Uses the "Skeleton & Flesh" architecture:
  - SKELETON (Python): HP, AC, Stats, Dice — calculated from archetype + player stats.
  - FLESH (LLM): Name, attack flavor text — generated by the Cartographer.

Archetypes:
  minion      → weak, dies fast, low damage
  skirmisher  → agile, moderate stats
  brute       → tanky, high damage, slow
  boss        → high HP, strong across the board

Fallback: If LLM data is missing, falls back to bestiary.json.
"""
import json
import math
import os
from typing import Optional, Dict, Any, List
from src.models.character import Character, Stat, Zone, Condition


# ── Combat Archetype Skeletons ────────────────────────────────────────────
# All math is pure Python. No LLM can touch these numbers.
ARCHETYPES = {
    "minion": {
        "hp_mult": 0.4,
        "ac_base": 10,
        "dice": "1d4",
        "stat_spread": {Stat.PHYS: 0, Stat.MENT: -1, Stat.SOC: -2},
        "inventory": [],
    },
    "skirmisher": {
        "hp_mult": 0.7,
        "ac_base": 12,
        "dice": "1d6",
        "stat_spread": {Stat.PHYS: 1, Stat.MENT: 0, Stat.SOC: -1},
        "inventory": ["rusty blade"],
    },
    "brute": {
        "hp_mult": 1.2,
        "ac_base": 11,
        "dice": "1d8",
        "stat_spread": {Stat.PHYS: 3, Stat.MENT: -1, Stat.SOC: -1},
        "inventory": ["heavy weapon"],
    },
    "boss": {
        "hp_mult": 2.5,
        "ac_base": 14,
        "dice": "2d6",
        "stat_spread": {Stat.PHYS: 2, Stat.MENT: 2, Stat.SOC: 1},
        "inventory": ["boss trophy", "healing potion"],
    },
}

# Minimum HP for any enemy — prevents 1HP rats
MIN_ENEMY_HP = 6


class EnemyFactory:
    """
    Generates enemy Character objects with Python-controlled math
    and LLM-provided flavor text.
    """

    @staticmethod
    def create(
        archetype: str,
        player: Character,
        enemy_name: str = "Unknown Creature",
        attack_flavor: str = "attacks",
        enemy_index: int = 1,
        extra_inventory: Optional[List[str]] = None,
    ) -> Character:
        """
        Creates a dynamically scaled enemy Character.

        Args:
            archetype: One of 'minion', 'skirmisher', 'brute', 'boss'.
            player: The player Character — enemy stats scale from this.
            enemy_name: LLM-generated display name (the "flesh").
            attack_flavor: LLM-generated attack description.
            enemy_index: For the enemy ID (e1, e2, etc.).
            extra_inventory: Additional items to add to the enemy's inventory.

        Returns:
            A fully constructed Character object ready for the combat loop.
        """
        # Sanitize archetype — fallback to skirmisher if unknown
        arch_key = archetype.lower().strip()
        if arch_key not in ARCHETYPES:
            arch_key = "skirmisher"

        arch = ARCHETYPES[arch_key]

        # ── Python-controlled math ────────────────────────────
        calculated_hp = max(MIN_ENEMY_HP, int(player.max_hp * arch["hp_mult"]))
        calculated_ac = arch["ac_base"]
        stats = dict(arch["stat_spread"])  # copy so we don't mutate the template

        # Build inventory
        inventory = list(arch["inventory"])
        if extra_inventory:
            inventory.extend(extra_inventory)

        # Store attack flavor in lore field so the Narrator can use it
        lore_text = f"Attack style: {attack_flavor}"

        return Character(
            id=f"e{enemy_index}",
            name=enemy_name,
            role=arch_key.capitalize(),
            hp=calculated_hp,
            max_hp=calculated_hp,
            ac=calculated_ac,
            stats=stats,
            zone=Zone.NEAR,
            inventory=inventory,
            condition=Condition.NORMAL,
            lore=lore_text,
        )

    @staticmethod
    def get_valid_archetypes() -> list:
        """Returns the list of valid archetype keys."""
        return list(ARCHETYPES.keys())
